sudo: required
services: 
  - docker

before_install:
  - docker build -t hepheastus45/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hepheastus45/docker-react npm test

after_success:
  - docker build -t hepheastus45/multi-client ./client
  - docker build -t hepheastus45/multi-nginx ./nginx
  - docker build -t hepheastus45/multi-server ./server
  - docker build -t hepheastus45/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push hepheastus45/multi-client
  - docker push hepheastus45/multi-nginx
  - docker push hepheastus45/multi-server
  - docker push hepheastus45/multi-worker